### ISSUE TITLE
Java error when installing

### ISSUE THREAD

**Issue by Flurrywinde** [Juraji/image-manager-2#3] opened 2019-04-03 18:54 UTC
I d/led the 2.0 release, then executed `java -jar image-manager-2.0.0-SNAPSHOT.jar` as the Releases page says. I got the following error:
```ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Error: Could not find or load main class nl.juraji.imagemanager.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
``` 
My system info:
```openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```

**Comment by Juraji** [comment] 2019-04-03 20:12
Hey @Flurrywinde,

That error means your Java environment (OpenJDK in your case) does not have the JavaFX plugin.
You need the Java JRE, on your Ubuntu system it's running `$ sudo apt install default-jre` from within your terminal. Check out [this website](https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-18-04), it has a step by step guide.

Note you can install the JRE alongside the your currently installed JDK.
I'll add a task to implement a fallback for systems without the JavaFX plugin.

Let us know if the solution worked!

**Comment by Flurrywinde** [comment] 2019-04-03 21:58
Hi, thanks for the help. `sudo apt install default-jre` by itself didn't work, so I installed `openjfx` as well, still no luck. Then I did `sudo update-alternatives --config java` and selected Java 8 instead of 11. Now it worked! Thanks again... except, now I'm actually trying to backup my images, and it's not working. Let me know if I should open new issues for each problem, but I figure maybe someone else with my system might have all the same issues too.

I was able to enter my login info and login. My two boards showed up in the list, but when I indexed them, it still said zero images afterwards. I did `System->View Logs`, but it froze. `kill` didn't work, so I did a `kill -9`. I opened it again and tried to `Open in Pinterest` one of the boards. It froze up again, and I had to `kill -9` again.

EDIT: I think maybe I was not able to actually log in. I have one secret board that didn't show up, and I believe, when accessing Pinterest via a browser, I am logging in via Google, not the username and password I put in in the Settings (which I guessed at and thought was successful). Will Image Manager 2 work if I log in that way and don't seem to have an actual Pinterest-only password?

**Comment by Juraji** [comment] 2019-04-04 13:01
Yes, I'd like new issues for new problems.

In response to your questions:
1. I've had more people stating Image Manager freezes on Ubuntu systems. Personally I've only used Image Manager on Windows and MacOSX. I have an Ubuntu 18.04 system, I shall be looking into it tonight.
As for the update-alternative fix and Java 11 to 8, I will put that in the README, so other people know.
2. I'm not sure how Pinterest does the Google login. Maybe I should have the user login via a browser window into Pinterest and persist the access token. But seeing as you were able to find boards, Image Manager was able to access your account. The not indexing issue could be caused by an issue fixed in the stable release, see #1 . Have you tried the latest release? You can simple replace the old JAR file with the new one, migration is automated. :D

I will create issues for these two.

**Comment by Juraji** [comment] 2019-04-08 19:11
If anyone else is running on Linux Ubuntu and having the `Could not find or load main class`-error.
Follow the steps on [the Installation Guide](https://github.com/Juraji/image-manager-2/wiki/Installation-Guide) in order to install the correct Java version.

**Comment by Juraji** [comment] 2019-04-08 19:12
I will close this issue since the initial issue is now resolved

**Closed as completed by Juraji** 2019-04-08 19:12 UTC
Labels: Support
